name: Create VCR marketplace package
run-name: ${{ github.actor }} is creating a new marketplace app release
on:
  release:
    types: [published]

permissions:
  actions: write
  checks: write
  contents: read
  deployments: write
  issues: read
  discussions: none
  packages: write
  pages: none
  pull-requests: read
  security-events: none
  statuses: write

jobs:
  create-zip-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Zip Release
        id: zip-release
        run: create-package.sh
      - name: Upload a Build Artifact
        id: upload-release-artifact
        uses: actions/upload-artifact@v4
        with:
          path: "./app.zip"
      - name: Output Artifact ID
        run: echo 'Artifact ID is ${{ steps.upload-release-artifact.outputs.artifact-id }}'
      - name: Create release from artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./app.zip"